# Generated by Django 5.0.1 on 2024-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_user',
            field=models.ImageField(default='media/user_default_image.png', upload_to='media/'),
        ),
    ]
